# Generated by Django 5.2.7 on 2025-11-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spin", "0003_add_mode_to_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="analysis_summary",
            field=models.TextField(blank=True, help_text="成功率分析の概要", null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="success_delta",
            field=models.IntegerField(
                blank=True, help_text="この発言による成功率変動", null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="last_analysis_reason",
            field=models.TextField(
                blank=True, help_text="直近の成功率変動理由", null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="success_probability",
            field=models.IntegerField(
                default=50, help_text="現在の商談成功率 (0-100%)"
            ),
        ),
    ]
